### ISSUE TITLE
Buy this book

### ISSUE THREAD

**Issue by Z3sty** [DineIn2018/dinein#18]
When I try to punch in/out, it keeps asking me to confirm a purchase of a book? lol wut??

**Comment by kassssc** [comment]
Which branch are you guys on? That book thing we got from some sample code we copied but we changed that already in our recent branches

**Comment by kassssc** [comment]
![img_0034](https://user-images.githubusercontent.com/36384578/39380171-3ec7c384-4a23-11e8-9234-89a7eda55f83.PNG)
