### ISSUE TITLE
Add Employee

### ISSUE THREAD

**Issue by Z3sty** [DineIn2018/dinein#19]
I think your phone number box should only accept numbers -- same with pay?
I think create and exit should be at the bottom -- the user is going to be viewing the bottom of the screen after finishing filling out the new employee form, the next thing expected is to create the user, not to quit :)
New employee was added twice after clicking create and exit?? (same userID)

**Comment by kassssc** [comment]
Yes we currently have a numpad show up so that the user could only type in numbers

**Comment by kassssc** [comment]
are you guys on the "TEST" branch? That has our latest code..
