### ISSUE TITLE
Unclear account creation confirmation

### ISSUE THREAD

**Issue by gracejohnsn** [DineIn2018/dinein#21]
Description: After creating an account, I am directed back to the login page where it appears that I can login with the information I entered on the account creation page, but no clear confirmation was available stating whether or not the account creation was successful, or instructing me to login with that information.

Severity: major - raises security concerns with authentication

**Comment by kassssc** [comment]
Thanks for pointing that out. We will add a confirmation alert saying the account creation was successful. In that version though, we have not integrated the database yet, so the create account currently does nothing.

**Comment by kassssc** [comment]
Confirmation has been added
