### ISSUE TITLE
Editing employee information

### ISSUE THREAD

**Issue by gracejohnsn** [DineIn2018/dinein#23]
Description: I am able to edit any employee's information and delete employees, though I'm not sure I should be able to as a regular user.

Severity: critical - raises security concerns, malicious users performing these actions could result in negative impacts on app data

Suggestions: These functions should maybe be reserved for restaurant owners/managers.

**Comment by kassssc** [comment]
That is a great point. Our app is intended for every employee to use, so we will add a pin authentication for manager features.

**Comment by kassssc** [comment]
Fixed for demo version. Added manager pin verification
