### ISSUE TITLE
View punch

### ISSUE THREAD

**Issue by gracejohnsn** [DineIn2018/dinein#26]
Description: After entering a time punch for a test employee with ID 9, I'm not able to see that punch when clicking "View Punch" from that employee's info page.

Severity: major - for restaurant management, would want this functionality to keep track of employees' shifts worked

**Comment by DonoStevenson** [comment]
As a note to this, punching in with a test employee and going through the list with ctrl+F doesn't show the employee in the punch list. Trying with a default employee has the same results.

**Comment by kassssc** [comment]
this is because our backend is not integrated yet, so no persistent data.
We are looking into that now.

**Comment by kassssc** [comment]
Issue fixed for demo.
