### ISSUE TITLE
Punching in with Invalid Employee ID

### ISSUE THREAD

**Issue by DonoStevenson** [DineIn2018/dinein#31]
Description : Entering any number into the punch card displays the same punch message, even if there is no employee assigned to that number.

Severity : Severe 
If there are no checks that an employee entered their ID number correctly or that the ID is even assigned, restaurants could be mistracking employee hours without realizing.

**Comment by monakona** [comment]
Suggestion: Maybe you could verify the ID when it is entered to see if it exists and in the modal confirm the user's name instead of just confirming the ID and time
