### ISSUE TITLE
Management tab header

### ISSUE THREAD

**Issue by monakona** [DineIn2018/dinein#33]
There seems to be an issue with the styling of the header in management tab. The headers for all the tabs can be seen except this one. It seems to be all the way in the corner in black. 
![screen shot 2018-04-30 at 4 52 36 pm](https://user-images.githubusercontent.com/37087754/39452228-19b7782a-4c97-11e8-80fc-200bebbe6ee0.png)
severity: cosmetic

**Comment by bsuzan06** [comment]
fixed!
