### ISSUE TITLE
Can enter anything for fields in Management Tab

### ISSUE THREAD

**Issue by DonoStevenson** [DineIn2018/dinein#34]
Description : ![dineinbug](https://user-images.githubusercontent.com/26578301/39452236-2212e9a0-4c97-11e8-8492-7ed76a691c3b.png)
Severity : 
Cosmetic if these aren't used for anything
Severe if these are used to determine restaurant capacity/total employees.

**Comment by kassssc** [comment]
This has been fixed for our demo version. The whole page was redesigned. Thank you for the feedback!
